In [2]:
#Impor Pustaka
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.models import model_from_yaml

#### Menyiapkan Data Testing

In [3]:
#data testing
data3=pd.read_csv('testbeasiswa.csv')
df3=pd.DataFrame(data3,columns=['Mahasiswa','IPK','Tingkat Kemiskinan (TM)','Beasiswa/Tidak'])
X3=np.asarray(data3)
x_test=X3[:,1:3]
y_test=X3[:,3:4]
x_test

array([[0.75, 0.74],
       [1.25, 1.16],
       [0.67, 1.69],
       [2.47, 3.19],
       [3.54, 2.45],
       [3.42, 3.86],
       [2.67, 3.47]])

#### Mengambil model JST dari File yaml

In [4]:
#Mengambil model JST dari File yaml
yaml_file = open('model.yaml', 'r')
loaded_model_yaml = yaml_file.read()
yaml_file.close()
loaded_model = model_from_yaml(loaded_model_yaml)
#Mengambil bobot JST
loaded_model.load_weights("model.h5")
print("Model JST diambil dari File")

Model JST diambil dari File


#### kompilasi model JST dan menguji dengan data test

In [5]:
#kompilasi model JST
loaded_model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])
#Prediksi
pred = loaded_model.predict(x_test)
print(pred)
print(y_test)
#Hitung Akurasi
loaded_model.evaluate(x=x_test, y=y_test, batch_size=None, verbose=1, sample_weight=None, steps=None)


[[0.49649695]
 [0.56886256]
 [0.55449325]
 [0.7920017 ]
 [0.81746775]
 [0.8696269 ]
 [0.81688493]]
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]]
7/7 [==============================] - 0s 6ms/step


[0.4446743428707123, 0.7142857313156128]